sudo: required
dist: trusty
# We can't use Clojure due to a premature call to lein prior to the
# before_install step by Travis CI. Calling lein before we've installed to the
# local Maven repo causes an error with lein-parent and Sonatype.
#language: clojure
language: java
install: test/support/travis_install.sh
# XXX for some reason, after_install is not executing on Travis for this
# project ...?
#after_install: test/support/setup_deps.sh
before_script: test/support/setup_deps.sh && lein version && lein deps && lein compile
script: make check
jdk:
  - oraclejdk8
  #- oraclejdk7
  #- openjdk8
  - openjdk7
env:
  - LD_LIBRARY_PATH=/usr/lib/jni
#addons:
#  apt:
#    sources:
#      -
notifications:
  email:
      # the following won't work until this Travis CI
      # bug is sorted:
      # https://github.com/travis-ci/travis-ci/issues/2513
      - lcmap-dev-notifications@googlegroups.com
      - duncan.mcgreggor.ctr@usgs.gov
  slack:
    rooms:
      - lcmap:UTqlh9PfPVomfpli10WKyZoh#cicd
      - lcmap:UTqlh9PfPVomfpli10WKyZoh#rest
